default:
  base_config:
    env_name: RayObstacleSquare
    unity_args:
      build_path:
        win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    reset_on_iteration: false
    n_envs: 10

  reset_config:
    force_reset: true

  sac_config:
    burn_in_step: 10
    n_step: 3
    seq_encoder: RNN
 
oc_2:
  base_config:
    name: oc2_{time}
  oc_config:
    num_options: 2

oc_3:
  base_config:
    name: oc3_{time}
  oc_config:
    num_options: 3

oc_4:
  base_config:
    name: oc4_{time}
  oc_config:
    num_options: 4
