default:
  base_config:
    env_name: UAVFoodCollector
    unity_args:
      build_path:
        win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64
      no_graphics: true

    n_envs: 50
    max_step: 500000
    reset_on_iteration: false

  reset_config:
    force_reset: true

  sac_config:
    write_summary_per_step: 1000 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 10
    seq_encoder: RNN

    # use_rnd: true
    # rnd_n_sample: 50
