default:
  base_config:
    env_name: Roller
    unity_args:
      build_path:
        win32: C:\Users\fisher\Documents\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    n_envs: 10
    reset_on_iteration: false

    update_sac_bak_per_step: 50 # Every N step update sac_bak for evaluation

    noise_increasing_rate: 0.01

  reset_config:
    force_reset: true

  sac_config:
    n_step: 3
    v_lambda: 0.99

visual:
  base_config:
    name: "{time}"
    nn: nn_visual

  net_config:
    evolver_host: visual-roller-ds-evolver

visual_hard:
  base_config: &visual_hard_base
    name: "hard_nopre_{time}"
    nn: nn_visual_hard
  net_config:
    evolver_host: visual-roller-hard-ds-evolver
  sac_config: &visual_hard_sac
    burn_in_step: 40
    seq_encoder: RNN

visual_hard_pre:
  base_config:
    <<: *visual_hard_base
    name: "hard_pre_{time}"
  net_config:
    evolver_host: visual-roller-hard-pre-ds-evolver
  sac_config:
    <<: *visual_hard_sac
    use_prediction: true

visual_hard_pre_noextra:
  base_config:
    <<: *visual_hard_base
    name: "hard_pre_noextra_{time}"
  net_config:
    evolver_host: visual-roller-hard-pre-noextra-ds-evolver
  sac_config:
    <<: *visual_hard_sac
    use_prediction: true
    use_extra_data: false
