default:
  base_config:
    env_name: USV
    unity_args:
      build_path:
        win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64
      no_graphics: false

    n_agents: 10
    reset_on_iteration: false

    evolver_enabled: false

  reset_config:
    force_reset: true

  sac_config:
    write_summary_per_step: 500 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 10
    seq_encoder: RNN

    use_rnd: true
    rnd_n_sample: 50

visual:
  base_config:
    name: "vis_{time}"
    nn: nn_visual

visual_nature:
  base_config:
    name: "vis_nature_{time}"
    nn: nn_visual_nature
