default:
  base_config:
    env_type: GYM
    env_name: Pendulum-v0

    max_step: -1
    max_iter: 100
    n_agents: 10

  sac_config:
    seed: 42

    n_step: 10

    tau: 0.9
    v_lambda: 0.99
    init_log_alpha: 0
