default:
  base_config:
    env_name: UGVChasing
    unity_args:
      build_path:
        win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
        linux: /data/linux-RL-Envs/RLEnvironments.x86_64
      no_graphics: false

    n_agents: 50
    max_step: 300000
    reset_on_iteration: false

  reset_config:
    force_reset: true
    bounding_box_random: 0

  nn_config:
    rep:
      ray_random: 0

  sac_config:
    write_summary_per_step: 1000 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps

    n_step: 3
    burn_in_step: 30
    seq_encoder: RNN

    v_lambda: 1

    use_rnd: true
    rnd_n_sample: 50

  ma_config:
    "UGV_Predator?team=0":
      sac_config:
        nn: nn_predator
    "UGV_Prey?team=0":
      sac_config:
        nn: nn_prey
