default:
  base_config:
    env_type: GYM
    scene: Walker2D

    build_path: "Walker2DBulletEnv-v0"

    n_agents: 10

  net_config:
    replay_host: 58.199.162.110
    replay_port: 61000
    learner_host: 58.199.162.110
    learner_port: 61001

  sac_config:
    write_summary_per_step: 100 # Write summaries in TensorBoard every N steps
    save_model_per_step: 10000 # Save model every N steps
    save_model_per_minute: 5 # Save model every N minutes

    n_step: 3
    _lambda: 0.99
    use_normalization: false

hard:
  base_config: &hard_base
    scene: Walker2DHard
    sac: sac_hard

  sac_config: &hard_sac
    burn_in_step: 20
    use_rnn: true
    use_prediction: true
