default:
  base_config:
    scene: 3DBall

    build_path:
      win32: D:\Unity\win-RL-Envs\RLEnvironments.exe
      linux: /data/linux-RL-Envs/RLEnvironments.x86_64

    max_iter: 200
    n_agents: 10

  replay_config:
    beta: 0.1
    beta_increment_per_sampling: 0

  sac_config:
    n_step: 5

    init_log_alpha: -4.6

hard_rnn:
  base_config:
    nn: nn_hard_rnn
    name: "hard_rnn_{time}"
  sac_config:
    seq_encoder: RNN
    burn_in_step: 10

hard_attn:
  base_config:
    nn: nn_hard_attn
    name: "hard_attn_{time}"
  sac_config:
    seq_encoder: ATTN
    burn_in_step: 10
