base_config:
  build_path: 
    win32: C:\Users\Fisher\Documents\Unity\build-RL-Envs\RL-Envs.exe
    linux: /data/linux-RL-Envs/RL-Envs.x86_64
  scene: 3DBallHard
  
  sac: sac_hard
  max_iter: 200
  max_step: 500
  save_model_per_iter: 20

replay_config:
  beta: 0.1
  beta_increment_per_sampling: 0

sac_config:
  seed: 42

  burn_in_step: 10
  n_step: 5
  use_rnn: true

  init_log_alpha: -4.6
  use_prediction: false
