default:
  base_config:
    env_type: GYM
    env_name: StackCorridor-v0

    name: rnn_{time}

    n_envs: 50

  reset_config:
    stack_len: 15
    stack_nesting: 0.5
    block_gap: 5
    success_reward: 2.
    failure_reward: -1.
    max_episode_steps: 200

  sac_config:
    burn_in_step: 5
    n_step: 3
    seq_encoder: RNN

    discrete_dqn_like: true

    # use_rnd: true
    # rnd_n_sample: 50

  oc_config:
    option_eplison: 0.2 # Probability of switching options
    terminal_entropy: 0.001 # Tending not to terminate >0, tending to terminate <0
    key_max_length: 300

attn:
  base_config:
    name: attn_{time}
  sac_config:
    nn: nn_attn
    seq_encoder: ATTN

oc_2:
  base_config:
    name: oc_2_rnn_{time}
  oc_config:
    num_options: 2

oc_3:
  base_config:
    name: oc_3_rnn_{time}
  oc_config:
    num_options: 3

oc_4:
  base_config:
    name: oc_4_rnn_{time}
  oc_config:
    num_options: 4

oc_2_dilated:
  inherited: oc_2
  base_config:
    name: oc_2_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_3_dilated:
  inherited: oc_3
  base_config:
    name: oc_3_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_4_dilated:
  inherited: oc_4
  base_config:
    name: oc_4_dilated_rnn_{time}
  oc_config:
    use_dilation: true

oc_2_attn:
  inherited:
    - oc_2
    - attn
  base_config:
    name: oc_2_attn_{time}

oc_3_attn:
  inherited:
    - oc_3
    - attn
  base_config:
    name: oc_3_attn_{time}

oc_4_attn:
  inherited:
    - oc_4
    - attn
  base_config:
    name: oc_4_attn_{time}

oc_2_attn_dilated:
  inherited: oc_2_attn
  base_config:
    name: oc_2_dilated_attn_{time}
  oc_config:
    use_dilation: true

oc_3_attn_dilated:
  inherited: oc_3_attn
  base_config:
    name: oc_3_dilated_attn_{time}
  oc_config:
    use_dilation: true

oc_4_attn_dilated:
  inherited: oc_4_attn
  base_config:
    name: oc_4_dilated_attn_{time}
  oc_config:
    use_dilation: true

oc_2_attn_dilated_te005:
  inherited: oc_2_attn
  base_config:
    name: oc_2_dilated_attn_te005_{time}
  oc_config:
    terminal_entropy: 0.005
    use_dilation: true

oc_3_attn_dilated_te005:
  inherited: oc_3_attn
  base_config:
    name: oc_3_dilated_attn_te005_{time}
  oc_config:
    terminal_entropy: 0.005
    use_dilation: true

oc_4_attn_dilated_te005:
  inherited: oc_4_attn
  base_config:
    name: oc_4_dilated_attn_te005_{time}
  oc_config:
    terminal_entropy: 0.005
    use_dilation: true

oc_2_attn_dilated_te001:
  inherited: oc_2_attn
  base_config:
    name: oc_2_dilated_attn_te001_{time}
  oc_config:
    terminal_entropy: 0.001
    use_dilation: true

oc_3_attn_dilated_te001:
  inherited: oc_3_attn
  base_config:
    name: oc_3_dilated_attn_te001_{time}
  oc_config:
    terminal_entropy: 0.001
    use_dilation: true

oc_4_attn_dilated_te001:
  inherited: oc_4_attn
  base_config:
    name: oc_4_dilated_attn_te001_{time}
  oc_config:
    terminal_entropy: 0.001
    use_dilation: true

oc_2_attn_dilated_te01:
  inherited: oc_2_attn
  base_config:
    name: oc_2_dilated_attn_te01_{time}
  oc_config:
    terminal_entropy: 0.01
    use_dilation: true

oc_3_attn_dilated_te01:
  inherited: oc_3_attn
  base_config:
    name: oc_3_dilated_attn_te01_{time}
  oc_config:
    terminal_entropy: 0.01
    use_dilation: true

oc_4_attn_dilated_te01:
  inherited: oc_4_attn
  base_config:
    name: oc_4_dilated_attn_te01_{time}
  oc_config:
    terminal_entropy: 0.01
    use_dilation: true
